apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-nodejs-demo
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            todo: web
    template:
        metadata:
            labels:
                todo: web
        spec:
            containers:
                - name: todo-site
                  image: possible7/docker_node
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: todo-entrypoint
    namespace: default
spec:
    type: NodePort
    selector:
        todo: web
    ports:
        - port: 5555
          targetPort: 5555
          nodePort: 30001
